### PR TITLE
Move from faucet/tape to mocha/expect.js and add "gulp test"

### PR DESCRIPTION
**Pull request by ibc**
This PR is a first step (if accepted) to "all based on gulp".

Running `gulp` executes the "lint" and "test" tasks. The "test" task uses [gulp-mocha](https://github.com/sindresorhus/gulp-mocha) and the tests under test/mocha/ use [expect.js](https://github.com/Automattic/expect.js).

### CODE REVIEW

**Comment by ibc** [comment]
BTW, please do not accept the PR. I prefer to know first your opinion and even if you like it I should figure out how to include the "compile" task into gulp.

I may also try another test units instead of expect.js (I may use mocha with tape, etc).

**Comment by theturtle32** [comment]
I'm totally on board with having gulp run the tests.  However I'm not super excited about Mocha for two reasons.

1.) I don't like "magic" things happening in code.  Functions (like `describe()` and `it()`) should not be added to the global scope by a test runner.

2.) I really dislike these cutesy testing DSLs that try (and fail, IMO) to make the tests read like english.  I would far prefer my tests to read like the same JavaScript code that I write the library in.  I really don't like this: `expect(myVariable).to.equal(4);` stuff.  I vastly prefer assertions that look and read like normal code: `t.equal(myVariable, 4);` or `t.assert(myVariable === 4);`

3.) I conceptually like the idea of TAP, and that it can be parsed and the results formatted in a pretty way by any third-party script or library that understands TAP.  I believe Mocha can be made to output TAP, but I'm not sold on using Mocha for the reasons above.

**Comment by theturtle32** [comment]
See also:
[TAP & Tape, the awesome way to test JavaScript](http://www.macwright.org/2014/03/11/tape-is-cool.html)
and:
Substack: "[how I write tests for node and the browser](http://substack.net/how_I_write_tests_for_node_and_the_browser)"

**Comment by theturtle32** [comment]
The reason I prefer assertions to be written more like normal code is that there's less to learn.  I don't want to constantly look up the documentation to learn the nuances of the testing DSL.  I want to write code to test my code in the language I already know.

**Comment by ibc** [comment]
I agree with you. I just tried mocha & expect.js since mocha integrates nice with gulp (there is `gulp-mocha` in fact`).

Let me some time to investigate about other testunit solutions including Tape (I need to make them properly work with gulp).

**Comment by ibc** [comment]
@theturtle32 I think this will like you:

gulpfile.js:

```
/**
 * Dependencies.
 */
var gulp = require('gulp');
var jshint = require('gulp-jshint');
var shell = require('gulp-shell');


gulp.task('lint', function() {
	return gulp.src(['gulpfile.js', 'lib/**/*.js', 'test/**/*.js'])
		.pipe(jshint('.jshintrc'))
		.pipe(jshint.reporter('jshint-stylish', {verbose: true}))
		.pipe(jshint.reporter('fail'));
});


gulp.task('test', shell.task(
	['node_modules/.bin/tape test/unit/*.js | node_modules/.bin/faucet']
));


gulp.task('default', gulp.series('lint', 'test'));
```

:)

**Comment by ibc** [comment]
Output of `gulp` command:

```
ibc@local in ~/src/WebSocket-Node $ gulp

[13:56:01] Using gulpfile ~/src/WebSocket-Node/gulpfile.js
[13:56:01] Starting 'default'...
[13:56:01] Starting 'lint'...
[13:56:02] Finished 'lint' after 969 ms
[13:56:02] Starting 'test'...
✓ Drop TCP Connection Before server accepts the request
✓ Request can only be rejected or accepted once.
✓ Protocol mismatch should be handled gracefully
✓ setup
✓ mismatched protocol connection
✓ teardown
✓ W3CWebSockets
✓ Serializing a WebSocket Frame with no data
# tests 19
# pass  19
✓ ok
[13:56:03] Finished 'test' after 941 ms
[13:56:03] Finished 'default' after 1.91 s
```

**Comment by theturtle32** [comment]
I do like the updated `test` task for Gulp.  The downside is that it won't work on Windows.  I'd be willing to accept a patch that looks like that for now, but we really should try to figure out a testing solution that will run properly under Windows environments.

**Comment by ibc** [comment]
Question: why do you say that it won't work on Windows? I mean, probably you are right :)

**Comment by theturtle32** [comment]
@ibc the call to shell.task() isn't Windows-friendly, because its argument is assuming a unix shell.

**Comment by theturtle32** [comment]
Closing this since it's been a while.

**Pull request closed without merging**
