### PR TITLE
adding compatibility with V8 release greater than v7.6 (node and electron engines)

### PR DESCRIPTION
**Pull request by artynet**
As described in the object, this set of patches enable the build compatibility against most recent releases of node.js/electron and the updated NAN APIs

### CODE REVIEW

**Comment by belcherj** [comment]
I have tested this PR to build on npm v12 and it works as expected!!

**Comment by ibc** [comment]
Nice! Does it also work with previous Node versions?

**Comment by ibc** [comment]
@theturtle32 any chance to check this? It's becoming a real need...

**Comment by artynet** [comment]
@ibc @belcherj I run a prebuild compiling test with :

```
$ npm install -g prebuild
$  prebuild --all
```
and it seems to build all the binary packages at least on Linux based systems. You might encounter some clashes on the most recent versions of OSX with the outdated releases of node/electron.

**Comment by orgads** [comment]
I just tested with Node 10, and it builds fine + all the tests pass.

Please accept the PR ASAP and release a new version.

Thanks!

**Comment by artynet** [comment]
@orgads thanks for your feedback !

**Comment by ibc** [comment]
Thanks for this PR and for confirming that it works in previous and new Node versions.

I'll merge this PR. However publishing a new NPM package depends on @theturtle32.

**Comment by artynet** [comment]
Thank you very much for merging my PR @ibc. I'm really glad for giving this contribution to the project !

**Comment by theturtle32** [comment]
I'll see if I can get to publishing this later today. Tomorrow at the latest.

**Comment by ibc** [comment]
Thanks @theturtle32

**Comment by artynet** [comment]
Thanks @theturtle32

**Comment by theturtle32** [comment]
Released v1.0.31 on npm.

**Comment by orgads** [comment]
Thank you!

**Pull request merged**
