### PR TITLE
adding the secure option to the docs

### PR DESCRIPTION
**Pull request by fresheneesz**

### CODE REVIEW

**Comment by theturtle32** [comment]
This is invalid. You cannot specify "secure" in the config to WebSocketClient. Instead, it derives whether it should make a secure connection based on whether the url starts with `ws:` or `wss:`

**Comment by fresheneesz** [comment]
@theturtle32 Ok, but I wasn't able to get wss working without specifying this option. Why does the option exist in the code and yet is not documented?

**Comment by theturtle32** [comment]
I'm pretty sure it does not, in fact, exist in the code. Can you paste a usage example?

**Comment by theturtle32** [comment]
Here's the line where the `secure` attribute is set:
https://github.com/theturtle32/WebSocket-Node/blob/5daf2f9ce3c11ba5f09d7743a52ee51570b791c7/lib/WebSocketClient.js#L148

```javascript
this.secure = (this.url.protocol === 'wss:');
```

**Comment by fresheneesz** [comment]
Hmm, looks like you're right. I must have misread something a year ago and confused it with something else.

**Comment by theturtle32** [comment]
No worries.

**Pull request closed without merging**
