### PR TITLE
Patch for https://github.com/theturtle32/WebSocket-Node/issues/288

### PR DESCRIPTION
**Pull request by tvkit**
Mitigate infinite loop for broken connections.

https://github.com/theturtle32/WebSocket-Node/issues/288

### CODE REVIEW

**Comment by tm1000** [comment]
Pretty sure this same thing is happening to me. It would be nice to get the fix in there @theturtle32

**Comment by tm1000** [comment]
Confirmed this patch works for me!

**Comment by ibc** [comment]
npm 1.0.25, please? :)

**Comment by theturtle32** [comment]
We really should revamp how events/closing is handled, I think, but until then yeah I will try to get this out in the next day or so.

**Comment by ibc** [comment]
So many thanks.

**Comment by theturtle32** [comment]
Published [v1.0.25](https://www.npmjs.com/package/websocket)

**Comment by quanguyen** [comment]
When my server ran with version 1.0.24, sometimes it got loop and did not accept any new connections. Does that relate to this problem and can be fixed by version 1.0.25?

**Comment by ibc** [comment]
@quanguyen that looks exactly that: the bug fixed in 1.0.25. Just upgrade.

**Pull request merged**
