### PR TITLE
Workaround postinstall malware in dependency

### PR DESCRIPTION
**Pull request by eolme**
Related: https://github.com/medikoo/es5-ext/blob/main/_postinstall.js

### CODE REVIEW

**Comment by ibc** [comment]
Which malware you mean?

**Comment by eolme** [comment]
@ibc just look at the file.

**Comment by ibc** [comment]
> @ibc just look at the file.

I did read the file. What I ask is: which malware you mean or why do you say that message is malware?

**Comment by eolme** [comment]
> > @ibc just look at the file.
> 
> I did read the file. What I ask is: which malware you mean or why do you say that message is malware?

Hah? You mean you guarantee that everything is all right? That there's an onion site too? I don't want to see messages about connecting to a botnet and calling for hate. Neither does anyone else.

**Comment by ibc** [comment]
> I don't want to see messages about connecting to a botnet and calling for hate.

I don't see any call for hate in that message. You may have another vision but you are just wrong.

**Pull request closed without merging**
