### PR TITLE
Fix browserify compatibility

### LINKED ISSUE #304: Microsoft Edge does not like the W3CWebSocket wrapper
Scenario:

A web application that uses browserify and a 3rd party JS library that uses `WebSocket-Node` to run in both browser and Node. So, when doing the browserify stuff, `lib/browser.js` is taken (which is just a wrapper of the native WebSocket in the browser).

However, Microsoft Edge 11 does not like it and fails ("invalid syntax"). It seems that `this` [here](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/browser.js#L1) does not point to `window` but to something strange (see the image):

screen shot 2017-12-08 at 02 57 25

I don't have an Edge browser so it will take some time before I can put my hands into this. In the meanwhile may be someone can help.

### PR DESCRIPTION
**Pull request by amateescu**
This change should fix #304.

### CODE REVIEW

**Comment by ibc** [comment]
Thanks, have you tested it in Edge?

**Comment by amateescu** [comment]
@ibc I have not and I don't have any Windows environment handy. But, since you opened the linked bug report, can you give it a try? :)

**Comment by ibc** [comment]
I don't have any Windows computer.

**Comment by theturtle32** [comment]
This fix isn't valid, because it'll just fall back to an empty object and the subsequent code won't be able to find the WebSocket constructor on that empty object.

**Pull request closed without merging**
